DROP TABLE Tags;
DROP TABLE Albums cascade constraints;
DROP TABLE Photos cascade constraints;
DROP TABLE Participants;
DROP TABLE User_Events;
DROP TABLE User_Current_Cities;
DROP TABLE User_Hometown_Cities;
DROP TABLE Cities;
DROP TABLE Messages;
DROP TABLE Education;
DROP TABLE Programs;
DROP TABLE Friends;
DROP TABLE Users;
DROP SEQUENCE city_seq;
DROP SEQUENCE program_seq;